import { GoogleSpreadsheet } from "google-spreadsheet";
import { JWT } from "google-auth-library";
import createMultipleCloudAccounts from "../controllers/accounts/AddAccountsToCloud";
import { accountData } from "../controllers/accounts/getCloudAccounts";
import deleteAccounts from "../controllers/accounts/deleteCloudAccounts";

// Initialize auth - see https://theoephraim.github.io/node-google-spreadsheet/#/guides/authentication
const serviceAccountAuth = new JWT({
  // env var values here are copied from service account credentials generated by google
  // see "Authentication" section in docs for more info
  email: process.env.GOOGLE_SERVICE_ACCOUNT_EMAIL,
  key: process.env.GOOGLE_PRIVATE_KEY,
  scopes: ["https://www.googleapis.com/auth/spreadsheets"],
});

const doc = new GoogleSpreadsheet(
  "1nUWAeKmStaNt72iHPfW1D-0EfONJVMRYH6RUGfMM--g",
  serviceAccountAuth
);
// await doc.loadInfo(); // loads document properties and worksheets
// console.log(doc.title);
// await doc.updateProperties({ title: "student list" });

interface RowData {
  [key: string]: any;
}

interface SheetData {
  shortName: string;
  fullName: string;
}

type type = "teacher" | "student" | "manager" | "security";

class StudentDataHandler {
  private doc: GoogleSpreadsheet; // Update 'any' with the actual type of 'doc'

  private teachers: string[] = ["teachers"];
  private managers: string[] = ["managers"];
  private securities: string[] = ["securities"];
  private gradeSheets: string[] = [
    "first-grade-c",
    "first-grade-y",
    "second-grade-c",
    "second-grade-y",
    "third-grade-c",
    "third-grade-y",
    "fourth-grade-c",
    "fourth-grade-y",
  ];

  private allStudents: SheetData[] = [];
  private allTeachers: SheetData[] = [];
  private allManagers: SheetData[] = [];
  private allSecurities: SheetData[] = [];

  private noneExitedStudents: SheetData[] = [];
  private noneExitedTeachers: SheetData[] = [];
  private noneExitedManagers: SheetData[] = [];
  private noneExitedSecurities: SheetData[] = [];

  constructor(doc: GoogleSpreadsheet) {
    this.doc = doc;
  }

  public async loadAllAccounts(max: number = 100): Promise<void> {
    await this.loadStudents(max);
    await this.loadTeachers(max);
    await this.loadManagers(max);
    await this.loadSecurities(max);
  }

  public async loadStudents(max: number = 100): Promise<void> {
    const promises = this.gradeSheets.map(async (sheet) => {
      const gradeSheet = this.doc.sheetsByTitle[sheet];
      if (gradeSheet) {
        await gradeSheet.loadCells(`A1:B${max}`);
        const rows = await gradeSheet.getRows();
        this.allStudents.push(
          ...rows.map((row) => row.toObject() as SheetData)
        );
      }
    });

    await Promise.all(promises);
  }
  public async loadTeachers(max: number = 100): Promise<void> {
    const promises = this.teachers.map(async (sheet) => {
      const gradeSheet = this.doc.sheetsByTitle[sheet];
      if (gradeSheet) {
        await gradeSheet.loadCells(`A1:B${max}`);
        const rows = await gradeSheet.getRows();
        this.allTeachers.push(
          ...rows.map((row) => row.toObject() as SheetData)
        );
      }
    });
    await Promise.all(promises);
  }

  public async loadManagers(max: number = 100): Promise<void> {
    const promises = this.managers.map(async (sheet) => {
      const gradeSheet = this.doc.sheetsByTitle[sheet];
      if (gradeSheet) {
        await gradeSheet.loadCells(`A1:B${max}`);
        const rows = await gradeSheet.getRows();
        this.allManagers.push(
          ...rows.map((row) => row.toObject() as SheetData)
        );
      }
    });

    await Promise.all(promises);
  }
  public async loadSecurities(max: number = 100): Promise<void> {
    const promises = this.securities.map(async (sheet) => {
      const gradeSheet = this.doc.sheetsByTitle[sheet];
      if (gradeSheet) {
        await gradeSheet.loadCells(`A1:B${max}`);
        const rows = await gradeSheet.getRows();
        this.allSecurities.push(
          ...rows.map((row) => row.toObject() as SheetData)
        );
      }
    });
    await Promise.all(promises);
  }

  public getAllStudents(): SheetData[] {
    return this.allStudents;
  }

  public getTeachers(): SheetData[] {
    return this.allTeachers;
  }

  public getAllManagers(): SheetData[] {
    return this.allManagers;
  }

  public getSecurities(): SheetData[] {
    return this.allSecurities;
  }

  public async uploadStudentsToFirebase(): Promise<boolean> {
    return await createMultipleCloudAccounts(this.allStudents, "student");
  }

  public async uploadTeachersToFirebase(): Promise<boolean> {
    return await createMultipleCloudAccounts(this.allTeachers, "teacher");
  }

  public async uploadManagersToFirebase(): Promise<boolean> {
    return await createMultipleCloudAccounts(this.allManagers, "manager");
  }

  public async uploadSecuritiesToFirebase(): Promise<boolean> {
    return await createMultipleCloudAccounts(this.allSecurities, "security");
  }

  public async addAndDeleteSheet(): Promise<void> {
    const newSheet = await this.doc.addSheet({ title: "another sheet" });
    await newSheet.delete();
  }

  public async updateStudentsInFirebase(
    sheetAccounts: SheetData[],
    firebaseAccount: accountData[]
  ): Promise<number> {
    this.noneExitedStudents = sheetAccounts.filter((gAccount) => {
      const isExistsAccount = firebaseAccount.find(
        (fAccount) => fAccount.fullName === gAccount.fullName
      );
      if (!isExistsAccount) return true;
    });
    if (!this.noneExitedStudents.length) return 0;
    createMultipleCloudAccounts(this.noneExitedStudents, "student");
    return this.noneExitedStudents.length;
  }

  public async updateTeachersInFirebase(
    sheetAccounts: SheetData[],
    firebaseAccount: accountData[]
  ): Promise<number> {
    this.noneExitedTeachers = sheetAccounts.filter((gAccount) => {
      const isExistsAccount = firebaseAccount.find(
        (fAccount) => fAccount.fullName === gAccount.fullName
      );
      if (!isExistsAccount) return true;
    });
    if (!this.noneExitedTeachers.length) return 0;
    createMultipleCloudAccounts(this.noneExitedTeachers, "teacher");
    return this.noneExitedTeachers.length;
  }

  public async updateManagersInFirebase(
    sheetAccounts: SheetData[],
    firebaseAccount: accountData[]
  ): Promise<number> {
    this.noneExitedManagers = sheetAccounts.filter((gAccount) => {
      const isExistsAccount = firebaseAccount.find(
        (fAccount) => fAccount.fullName === gAccount.fullName
      );
      if (!isExistsAccount) return true;
    });
    if (!this.noneExitedManagers.length) return 0;
    createMultipleCloudAccounts(this.noneExitedManagers, "manager");
    return this.noneExitedManagers.length;
  }

  public async updateSecuritiesInFirebase(
    sheetAccounts: SheetData[],
    firebaseAccount: accountData[]
  ): Promise<number> {
    this.noneExitedSecurities = sheetAccounts.filter((gAccount) => {
      const isExistsAccount = firebaseAccount.find(
        (fAccount) => fAccount.fullName === gAccount.fullName
      );
      if (!isExistsAccount) return true;
    });
    if (!this.noneExitedSecurities.length) return 0;
    createMultipleCloudAccounts(this.noneExitedSecurities, "manager");
    return this.noneExitedSecurities.length;
  }

  public async uploadAllAccounts(): Promise<boolean> {
    const studentsCount = await this.uploadStudentsToFirebase();
    const TeachersCount = await this.uploadTeachersToFirebase();
    const ManagersCount = await this.uploadManagersToFirebase();
    const securitiesCount = await this.uploadSecuritiesToFirebase();

    return studentsCount && TeachersCount && ManagersCount && securitiesCount;
  }

  public async deleteAllStudents() {
    await deleteAccounts(["student"]);
  }

  public async deleteAllTeachers() {
    await deleteAccounts(["teacher"]);
  }

  public async deleteAllManagers() {
    await deleteAccounts(["manager"]);
  }

  public async deleteAllSecurities() {
    await deleteAccounts(["security"]);
  }

  public async deleteAllAccounts() {
    await deleteAccounts();
  }
}

const spreed = async (): Promise<void> => {
  const doc = new GoogleSpreadsheet(
    process.env.ACCOUNT_LISTS_SHEETS as string,
    serviceAccountAuth
  );
  const handler = new StudentDataHandler(doc);
  //   handler.deleteAllAccounts();
  //   await doc.loadInfo();

  //   await handler.loadAllAccounts();
  //   handler.uploadAllAccounts();
  //   handler.getAllStudents();

  //   console.log(doc.title);
  //   await doc.updateProperties({ title: "account lists" });
};

export default spreed;
// getAccounts
